{"cve": {"id": "CVE-2024-9774", "sourceIdentifier": "secalert@redhat.com", "published": "2024-12-27T02:15:07.330", "lastModified": "2024-12-27T02:15:07.330", "vulnStatus": "Received", "cveTags": [], "descriptions": [{"lang": "en", "value": "A vulnerability was found in python-sql where unary operators do not escape non-Expression."}], "metrics": {"cvssMetricV30": [{"source": "secalert@redhat.com", "type": "Secondary", "cvssData": {"version": "3.0", "vectorString": "CVSS:3.0/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:H/A:N", "baseScore": 6.5, "baseSeverity": "MEDIUM", "attackVector": "NETWORK", "attackComplexity": "LOW", "privilegesRequired": "HIGH", "userInteraction": "NONE", "scope": "UNCHANGED", "confidentialityImpact": "HIGH", "integrityImpact": "HIGH", "availabilityImpact": "NONE"}, "exploitabilityScore": 1.2, "impactScore": 5.2}]}, "weaknesses": [{"source": "secalert@redhat.com", "type": "Primary", "description": [{"lang": "en", "value": "CWE-150"}]}], "references": [{"url": "https://discuss.tryton.org/t/security-release-for-issue-93/7889/3", "source": "secalert@redhat.com"}]}}