{"cve": {"id": "CVE-2024-50113", "sourceIdentifier": "416baaa9-dc9f-4396-8d5f-8c081fb06d67", "published": "2024-11-05T18:15:14.560", "lastModified": "2024-11-06T18:17:17.287", "vulnStatus": "Awaiting Analysis", "cveTags": [], "descriptions": [{"lang": "en", "value": "In the Linux kernel, the following vulnerability has been resolved:\n\nfirewire: core: fix invalid port index for parent device\n\nIn a commit 24b7f8e5cd65 (\"firewire: core: use helper functions for self\nID sequence\"), the enumeration over self ID sequence was refactored with\nsome helper functions with KUnit tests. These helper functions are\nguaranteed to work expectedly by the KUnit tests, however their application\nincludes a mistake to assign invalid value to the index of port connected\nto parent device.\n\nThis bug affects the case that any extra node devices which has three or\nmore ports are connected to 1394 OHCI controller. In the case, the path\nto update the tree cache could hits WARN_ON(), and gets general protection\nfault due to the access to invalid address computed by the invalid value.\n\nThis commit fixes the bug to assign correct port index."}, {"lang": "es", "value": " En el kernel de Linux, se ha resuelto la siguiente vulnerabilidad: firewire: core: fix invalid port index for parent device En una confirmaci\u00f3n 24b7f8e5cd65 (\"firewire: core: use helper functions for self ID sequence\"), la enumeraci\u00f3n sobre la secuencia de auto-identificaci\u00f3n se refactoriz\u00f3 con algunas funciones auxiliares con pruebas KUnit. Se garantiza que estas funciones auxiliares funcionar\u00e1n como se espera mediante las pruebas KUnit, sin embargo, su aplicaci\u00f3n incluye un error para asignar un valor no v\u00e1lido al \u00edndice del puerto conectado al dispositivo principal. Este error afecta al caso en que cualquier dispositivo de nodo adicional que tenga tres o m\u00e1s puertos est\u00e9 conectado al controlador 1394 OHCI. En el caso, la ruta para actualizar la cach\u00e9 del \u00e1rbol podr\u00eda alcanzar WARN_ON() y obtener un fallo de protecci\u00f3n general debido al acceso a una direcci\u00f3n no v\u00e1lida calculada por el valor no v\u00e1lido. Esta confirmaci\u00f3n corrige el error para asignar el \u00edndice de puerto correcto."}], "metrics": {}, "references": [{"url": "https://git.kernel.org/stable/c/90753a38bc3d058820981f812a908a99f7b337c1", "source": "416baaa9-dc9f-4396-8d5f-8c081fb06d67"}, {"url": "https://git.kernel.org/stable/c/f6a6780e0b9bbcf311a727afed06fee533a5e957", "source": "416baaa9-dc9f-4396-8d5f-8c081fb06d67"}]}}