{"cve": {"id": "CVE-2025-32911", "sourceIdentifier": "secalert@redhat.com", "published": "2025-04-15T16:16:06.567", "lastModified": "2025-04-28T11:15:38.547", "vulnStatus": "Awaiting Analysis", "cveTags": [], "descriptions": [{"lang": "en", "value": "A use-after-free type vulnerability was found in libsoup, in the soup_message_headers_get_content_disposition() function. This flaw allows a malicious HTTP client to cause memory corruption in the libsoup server."}, {"lang": "es", "value": "Se encontr\u00f3 una falla en libsoup, vulnerable a un problema de use-after-free que no se encuentra en el mont\u00f3n en la funci\u00f3n soup_message_headers_get_content_disposition(). Esta falla permite que un cliente HTTP malicioso cause corrupci\u00f3n de memoria en el servidor libsoup."}], "metrics": {"cvssMetricV31": [{"source": "secalert@redhat.com", "type": "Secondary", "cvssData": {"version": "3.1", "vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:H/I:H/A:H", "baseScore": 9.0, "baseSeverity": "CRITICAL", "attackVector": "NETWORK", "attackComplexity": "HIGH", "privilegesRequired": "NONE", "userInteraction": "NONE", "scope": "CHANGED", "confidentialityImpact": "HIGH", "integrityImpact": "HIGH", "availabilityImpact": "HIGH"}, "exploitabilityScore": 2.2, "impactScore": 6.0}]}, "weaknesses": [{"source": "secalert@redhat.com", "type": "Secondary", "description": [{"lang": "en", "value": "CWE-590"}]}], "references": [{"url": "https://access.redhat.com/security/cve/CVE-2025-32911", "source": "secalert@redhat.com"}, {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2359355", "source": "secalert@redhat.com"}]}}